// AUTO-GENERATED by content-pipeline/scripts/export_seed_ts.py — do not hand-edit.
// Regenerate with: python3 export_seed_ts.py <json_dir> <out_ts_path>
// Source of truth is the curriculum markdown in content-pipeline/curriculum-source/.

export type LessonSeed = {
  num: string;
  title: string;
  durationMin: number;
  objective: string;
  openingLine: string;
  bullets: string[];
};

export type ModuleSeed = {
  num: number;
  title: string;
  framing: string;
  lessons: LessonSeed[];
  workbookItems: string[];
};

export type CourseStatus = 'draft' | 'published' | 'archived';
export type CourseTier = 'single' | 'bundle' | 'full_access';

export type CourseSeed = {
  id: string;
  title: string;
  promise: string;
  who: string;
  price: number;
  tier: CourseTier;
  status: CourseStatus;
  slug: string;
  modules: ModuleSeed[];
};

export const COURSES: CourseSeed[] = [
  {
    id: "c1",
    title: "Build Your Digital Empire",
    promise: "by the end of this course, a learner has taken one skill she already has and turned it into a digital product she can sell — with a name, a home online, a price, and a way to launch it — without needing a team, a following, or a business degree.",
    who: "a woman with a skill, a following, or a point of view, who has been circling \"I should sell something\" for months without a clear next step.",
    price: 149,
    tier: 'single',
    status: "published",
    slug: "build-your-digital-empire",
    modules: [
      {
        num: 1,
        title: "The Idea Layer",
        framing: "most women don't have an idea problem, they have a decision problem — too many half-ideas and no way to pick one. This module is entirely about narrowing.",
        lessons: [
          {
            num: "1.1",
            title: "Turning a Skill Into a Sellable Product",
            durationMin: 10,
            objective: "the learner can name three of her own skills and recognize which ones are already \"sellable\" versus which need translating into a result.",
            openingLine: "You don't need a new skill to build this — you need to stop underpricing the one you already have.",
            bullets: ["Open with the core reframe: a sellable product isn't a new skill, it's an existing skill made transferable — something she already does that someone else would pay to shortcut.", "Walk through the three sources most first products come from: something people already ask her for, something she had to teach herself the hard way, and something she does faster or better than most people around her.", "Give the test for whether a skill is \"sellable\" yet: can she describe the RESULT it gets someone, not just the activity itself (not \"I'm good at budgeting,\" but \"I get people to their first $1,000 saved in 60 days\").", "Run through 3–4 real-feeling examples across different skill types (organizing, cooking, systems, styling, parenting logistics) so no viewer feels like this only works for \"online business\" skills.", "Close by having her write down every skill she can think of in two minutes, no filtering yet — filtering is lesson 1.3's job."],
          },
          {
            num: "1.2",
            title: "Finding the Woman You're Building For",
            durationMin: 8,
            objective: "the learner can describe her ideal buyer as a specific person with a specific problem, not a demographic.",
            openingLine: "The riches are in the specifics — let's find the one woman you're actually talking to.",
            bullets: ["Name the mistake: building the product before deciding who it's for, which is why so many first products feel like they're for \"everyone\" and sell to no one.", "Teach the difference between a demographic (\"women 25–40\") and a buyer (\"a woman who just got promoted and has no idea how to budget on a bigger paycheck\") — the second one you can actually write a sales page to.", "Give three questions to find her: who was I before I learned this? Who do I already talk to about this for free? Whose version of this problem do I understand best?", "Address the fear directly: narrowing the buyer doesn't shrink the market, it sharpens the message — a product \"for everyone\" reads as a product for no one.", "Have her write one sentence: \"I help ______ do ______ so they can ______.\""],
          },
          {
            num: "1.3",
            title: "Naming and Positioning Your Offer",
            durationMin: 12,
            objective: "the learner leaves with a working name and a one-line positioning statement for her offer.",
            openingLine: "A great name does half your selling for you — here's how to find yours.",
            bullets: ["Bring back her list from 1.1 and her buyer from 1.2, and show how to cross them to land on the one idea worth building first.", "Give the naming framework: name it for the transformation, not the format — \"The 60-Day Save\" beats \"My Budgeting Guide.\"", "Cover the three naming traps to avoid: too clever (no one remembers it), too generic (sounds like everyone else's), too jargon-y (buyer has to ask what it means).", "Teach the one-line positioning formula: \"[Product name] helps [buyer] go from [before state] to [after state] in [timeframe/format].\"", "Have her write three name options and pressure-test each against the positioning line before picking one to move forward with in Module 2."],
          },
        ],
        workbookItems: ["Skill inventory: three columns to fill in — \"Things people already ask me for,\" \"Things I taught myself the hard way,\" \"Things I do faster than most people I know.\"", "Sellable-skill test: for each skill listed, a line to write the RESULT it gets someone (not the activity).", "Buyer sketch: name, age range, one sentence on where she is in life, one sentence on the specific problem she has right now.", "The one-line formula, fill-in-the-blank: \"I help ______ do ______ so they can ______.\"", "Naming shortlist: three name options, plus a checkbox next to each for \"passes the positioning test.\""],
      },
      {
        num: 2,
        title: "Your Digital Product",
        framing: "this is where most people either freeze (too many format options) or over-build (a 40-page guide when a 6-page one would sell). The module's job is to make the format decision fast and the build process faster.",
        lessons: [
          {
            num: "2.1",
            title: "Choosing the Right Format",
            durationMin: 9,
            objective: "the learner picks one product format based on her buyer's habits, not her own preference.",
            openingLine: "The best first product is the smallest one that still keeps your promise.",
            bullets: ["List the five most common first-product formats: PDF guide/workbook, templates, a short video course, a checklist/toolkit, a done-with-you notion or spreadsheet system.", "Teach the real deciding factor: not \"what am I most comfortable making\" but \"how does my buyer already like to consume things\" — a busy mom wants a checklist, not a 90-minute video.", "Cover the \"smallest viable version\" idea: the first product should be the smallest thing that still fully delivers the promise from Module 1 — bigger can come later as an upsell.", "Warn against the two most common format mistakes: building a course when a template would do, and building a template when the buyer actually needs to be walked through something.", "Have her commit to one format in writing before the next lesson."],
          },
          {
            num: "2.2",
            title: "Outlining It in One Sitting",
            durationMin: 14,
            objective: "the learner leaves with a complete outline of her product's content, start to finish.",
            openingLine: "You can build this in one sitting if you outline it before you decorate it.",
            bullets: ["Introduce the \"outline before you open a design tool\" rule — most stalled products stalled because someone opened Canva before they knew what the pages said.", "Teach the simple three-part shape almost every first product follows: where the buyer starts (the problem, named back to her), the method (the steps, in order), and where she ends up (the result, plus what's next).", "Model turning the positioning line from Lesson 1.3 into a table of contents — each \"step\" in the method becomes a section or module.", "Give the 20-minute timer trick: set a timer, write section headers and one sentence per section with no editing, to get the whole shape down before perfectionism sets in.", "Address scope creep directly: if a section doesn't serve the ONE promise, cut it — it can become a future product."],
          },
          {
            num: "2.3",
            title: "Building It in Canva and Notion",
            durationMin: 18,
            objective: "the learner has a first draft of her actual product file, built from the outline.",
            openingLine: "Open Canva and Notion beside me. We build the actual deliverable — cover, contents, worksheets — in one sitting, then export it the way buyers expect to receive it.",
            bullets: ["Screen-share style walkthrough: open Canva and Notion side by side, and show turning yesterday's outline into real pages — this is the one lesson that should feel like sitting next to her while she builds.", "Cover picking a Canva template that matches her brand quickly rather than starting from a blank page (link to a few pre-vetted templates in the resources).", "Show the actual build order: cover page, table of contents, then working straight down her outline section by section, dropping in placeholder text first and refining second.", "Demonstrate exporting a clean, on-brand PDF from Canva, and — for tool-based products — setting up the matching Notion template with the same structure.", "Close with a realistic timeline: this lesson is the longest because the build itself takes real focused time; encourage her to block 2–3 hours rather than expecting to finish while watching."],
          },
        ],
        workbookItems: ["Format decision: five formats listed with a line under each for \"why this would/wouldn't fit my buyer,\" ending in one circled choice.", "One-sitting outline template: numbered section slots (start with 5) with a line each for section title and one-sentence summary.", "Build checklist: cover page, table of contents, each outlined section, worksheets/templates included, export format — a checkbox next to each.", "\"Cut list\": a space to note anything tempting to add that doesn't serve the one core promise, to save for a future product instead."],
      },
      {
        num: 3,
        title: "The Home You Own",
        framing: "a product needs a home that isn't a social platform's algorithm. This module gets her a site and a sales page she owns.",
        lessons: [
          {
            num: "3.1",
            title: "Setting Up a Site That Sells",
            durationMin: 16,
            objective: "the learner has a live, simple website or storefront page with her product ready to list.",
            openingLine: "You don't need a website, you need one page that can take a payment — let's build that today.",
            bullets: ["Reframe the goal: not a full website, just one page that can take a payment — perfection here is the enemy of launching.", "Compare the two realistic paths for this course's audience: a no-code storefront/link-in-bio-plus-checkout tool for the fastest launch, versus a simple site builder for someone who wants more brand control — give a clear recommendation for \"if you've never done this before.\"", "Walk through the essential page elements in order: headline, one clear image or mockup of the product, the price and buy button, and a short trust element (who she is, why she's credible on this).", "Cover the technical minimum: connecting a payment processor, testing a $1 purchase to confirm the flow works, and where the digital file actually gets delivered after purchase.", "Set the standard: this page does not need to be beautiful today, it needs to be able to take money today."],
          },
          {
            num: "3.2",
            title: "Writing a Sales Page in Your Voice",
            durationMin: 13,
            objective: "the learner has full sales page copy written, in her own voice, following a proven structure.",
            openingLine: "A sales page isn't a pitch, it's you explaining this to a friend who's exactly the person you built it for.",
            bullets: ["Give the sales page skeleton: a headline naming the transformation, three to five bullets on what's inside, a short \"this is for you if\" section, the price with what's included, and an FAQ addressing the top two hesitations.", "Teach writing \"in her voice\" as translating the positioning line from Module 1 into how she actually talks — read two contrasting examples, one generic and one voice-driven, so the difference is audible.", "Cover objection-handling directly: name the real hesitation a buyer has (\"will this actually work for someone like me\") and answer it in the FAQ instead of hoping it doesn't come up.", "Give a fill-in-the-blank first draft process: write the headline last, not first — pull it from whatever sentence in her rough draft feels most true.", "Close with a rule: the page is done when it sounds like something she'd actually say out loud to a friend, not like marketing copy."],
          },
        ],
        workbookItems: ["Platform decision worksheet: two columns (storefront tool vs. site builder) with space to note which fits her comfort level and timeline, ending in one choice.", "Page-element checklist: headline, product image, price and buy button, credibility line, tested purchase — checkboxes for each as she builds.", "Sales page skeleton: headline, 3–5 bullets, \"this is for you if,\" price/what's included, FAQ (2 questions minimum) — fill-in sections in order.", "Voice check: a space to paste her draft headline and rewrite it as if she were texting a friend, side by side."],
      },
      {
        num: 4,
        title: "Getting Paid",
        framing: "pricing is where confidence and logistics collide. This module handles both — the number, and the actual mechanics of collecting it.",
        lessons: [
          {
            num: "4.1",
            title: "Pricing Without Apologising",
            durationMin: 11,
            objective: "the learner sets a specific launch price and can explain why, without hedging.",
            openingLine: "Say the price out loud before you type it — if you flinch, we're fixing that flinch, not the price.",
            bullets: ["Open with the pattern to break: pricing based on what feels comfortable to charge rather than what the transformation is actually worth.", "Give three pricing anchors to consider: what similar products in her space charge, what a client would pay her for this 1:1, and the $120–$160 range that tends to work for a focused single product like this one.", "Address the two fears directly — \"no one will pay that\" and \"what if I priced it wrong\" — and normalize adjusting price after launch based on real data, not guessing forever before starting.", "Teach the psychology of round vs. non-round pricing briefly (e.g., $149 vs. $150) and let her choose what fits her brand.", "Have her commit to a launch price on the page, out loud, before moving on."],
          },
          {
            num: "4.2",
            title: "Checkout, Delivery and Receipts",
            durationMin: 15,
            objective: "the learner has a fully tested purchase-to-delivery flow, with no manual steps required on her end.",
            openingLine: "If you have to manually do anything every time someone buys, this lesson isn't done yet — let's automate the whole handoff.",
            bullets: ["Map the full buyer journey after \"buy now\": payment, confirmation email, product delivery, receipt — and show where each of those actually happens in her chosen tool from Module 3.", "Walk through setting up automatic product delivery (download link or access grant) so she is never manually emailing files to buyers.", "Cover receipts and basic bookkeeping hygiene: keeping a simple record of every sale for tax purposes, even at small volume.", "Show how to test the entire flow herself with a real transaction before telling anyone the product exists.", "Set the expectation: if any step of this requires her to do something by hand every time someone buys, it isn't finished yet."],
          },
        ],
        workbookItems: ["Pricing worksheet: three anchor prices (competitor, 1:1 rate, category range) with her final launch price circled and one sentence on why.", "Delivery flow map: five steps (payment → confirmation → delivery → receipt → records) with a checkbox confirming each is automated.", "Test-purchase log: date, amount, what worked, what needs fixing before real launch."],
      },
      {
        num: 5,
        title: "Content That Sells Softly",
        framing: "this is not a marketing bootcamp — it's a sustainable rhythm that doesn't require being \"on\" all day.",
        lessons: [
          {
            num: "5.1",
            title: "The Three-Post Rhythm",
            durationMin: 10,
            objective: "the learner can plan a week of content using three repeatable post types.",
            openingLine: "You only need three kinds of posts — let's make sure you never run out of what to say.",
            bullets: ["Introduce the three post types that do almost all the work: the problem post (naming the pain point her buyer has), the proof post (a result, testimonial, or behind-the-scenes of the product working), and the invitation post (a direct, low-pressure call to check out the offer).", "Show real example captions for each type, written in the \"soft\" tone — confident, warm, no hustle-culture pressure language.", "Teach the ratio that keeps it sustainable: roughly two problem/proof posts for every one direct invitation, so the audience doesn't feel sold to constantly.", "Cover format flexibility: the same three post types work as a caption, a short video script, or a carousel — the type matters more than the format.", "Have her draft one of each type for her actual offer before the next lesson."],
          },
          {
            num: "5.2",
            title: "Batching a Month in a Day",
            durationMin: 12,
            objective: "the learner leaves with a month of content mapped and a batching system she can repeat.",
            openingLine: "One focused day can cover your whole month — here's exactly how to structure it.",
            bullets: ["Make the case for batching: content posted \"in the moment\" is where burnout comes from — batching separates creating from showing up.", "Walk through a simple monthly content calendar using the three-post rhythm from 5.1, filling four weeks in about twenty minutes.", "Give a lightweight batching process: write all captions first in one sitting, then record/design visuals in a second sitting, then schedule everything in a third.", "Recommend a basic scheduling tool so posting doesn't depend on remembering to do it live every day.", "Close with the permission slip: a month planned in a day means the rest of the month is free to actually run the business."],
          },
        ],
        workbookItems: ["Three-post-type worksheet: a blank draft slot for one problem post, one proof post, and one invitation post.", "Monthly calendar grid: four weeks, three post slots per week, pre-labeled with post type so the rhythm is built in.", "Batching schedule: three time blocks to fill in (write captions, create visuals, schedule) with target dates."],
      },
      {
        num: 6,
        title: "The Quiet Launch",
        framing: "a launch that doesn't require becoming a different, louder person — just a plan and some warm-up.",
        lessons: [
          {
            num: "6.1",
            title: "Your Seven-Day Launch Plan",
            durationMin: 17,
            objective: "the learner has a day-by-day plan for launch week.",
            openingLine: "A launch isn't one big moment, it's seven small ones — let's map yours.",
            bullets: ["Reframe \"launch\" as a week-long conversation, not a single announcement post — most sales come from the follow-up, not the first mention.", "Walk through a full seven-day skeleton: days 1–2 warm-up (teasing the problem, no offer yet), day 3 the announcement, days 4–5 proof and FAQs, day 6 a direct case for buying now, day 7 last-call and close.", "Cover what to do on each day in practical terms: which post type from Module 5 fits, whether it's a story, a post, or an email.", "Address launch-week nerves directly: quiet doesn't mean invisible — it means steady and repeated, not loud and one-time.", "Have her fill in her own seven-day calendar with real dates before the module ends."],
          },
          {
            num: "6.2",
            title: "Warming Your List Before You Ask",
            durationMin: 9,
            objective: "the learner has a plan to engage her existing audience or email list before asking them to buy.",
            openingLine: "Before you ask anyone to buy, make sure they already feel like you've been talking to them.",
            bullets: ["Teach the core idea: people buy from someone they feel is already talking to them, not someone who shows up once to sell.", "Give three low-effort warm-up moves: a poll or question sticker about the problem her product solves, sharing a personal story connected to why she built it, and a \"coming soon\" mention with no link, just curiosity.", "Cover list-building basics for anyone starting from zero: a simple lead magnet or waitlist so there's at least a small warm audience by launch day.", "Address the size myth directly: a warm list of 50 people who trust her outsells a cold list of 5,000 who don't.", "Close by having her schedule at least one warm-up touchpoint before day 3 of her launch plan."],
          },
        ],
        workbookItems: ["Seven-day launch calendar: days 1–7, each with a line for the day's theme and the specific post/email planned.", "Warm-up tracker: three planned touchpoints (poll/question, personal story, coming-soon mention) with target dates.", "List-building note: current list/audience size, and one action to grow it before launch if starting small."],
      },
      {
        num: 7,
        title: "Soft Systems",
        framing: "the module that makes this a business instead of a one-time project — the parts that run without her.",
        lessons: [
          {
            num: "7.1",
            title: "Automating Delivery and Emails",
            durationMin: 14,
            objective: "the learner has automated the emails a buyer receives after purchase, without writing them one by one.",
            openingLine: "Let's make sure every buyer gets a warm welcome and a nudge to finish — without you writing a single email by hand.",
            bullets: ["Revisit the delivery flow from Module 4 and layer in email automation: a welcome/how-to-use email, an inactivity nudge for buyers who haven't started, and a completion email with a next-offer recommendation.", "Show setting up these three emails once inside her existing email tool, connected to the purchase or course-completion trigger, so they send themselves.", "Cover writing each email briefly and warmly — this should sound like her checking in, not an automated corporate sequence.", "Address the \"I don't have an email tool yet\" case with a simple, low-cost starting recommendation.", "Set the finish line: once these three emails are live, every future buyer gets the same thoughtful experience without her doing anything."],
          },
          {
            num: "7.2",
            title: "Reading Your Numbers Once a Month",
            durationMin: 8,
            objective: "the learner has a simple monthly check-in routine for her product's performance.",
            openingLine: "Once a month, five minutes — that's all it takes to keep this business honest and improving.",
            bullets: ["Introduce the short list of numbers that actually matter at this stage: sales this month, completion rate (are buyers finishing it), and where sales are coming from (which platform, which post).", "Teach a five-minute monthly review process rather than obsessive daily checking — sustainability over hustle.", "Show how to use what she learns: doubling down on whichever content type is actually driving sales, and revisiting pricing or the sales page if completion or conversion is low.", "Address the emotional side: a slow month is data, not a verdict — the review is there to inform the next month, not to spiral about the last one.", "Close the course by connecting back to Module 1: she now owns a real, sellable, systemized product — and the numbers review is what keeps it improving on its own schedule, not hers every day."],
          },
        ],
        workbookItems: ["Email automation checklist: welcome email, inactivity nudge, completion email — each with a checkbox and a one-line note on its trigger.", "Monthly numbers log: a repeatable table with columns for month, sales, completion rate, and top traffic source, with 3 blank rows to start filling in after launch.", "Course close-out: a short reflection prompt — \"the one thing I'm proudest I built in this course is ___\" and \"the next product I might build is ___.\""],
      },
    ],
  },
  {
    id: "c2",
    title: "The Soft Life Financial Reset",
    promise: "by the end of this course, a learner has a calm, honest picture of where her money actually stands, a budget she can keep for longer than a week, a plan for her debt, a real emergency fund started, and a one-year map toward the goals that matter to her.",
    who: "a woman who feels like she \"should\" have her money together by now, who has avoided looking closely at it out of shame rather than not caring — this course replaces the shame with a system.",
    price: 149,
    tier: 'single',
    status: "draft",
    slug: "the-soft-life-financial-reset",
    modules: [
      {
        num: 1,
        title: "Money Without the Shame",
        framing: "nothing in this course works until the shame spiral is interrupted first. This module is short on purpose — it's permission, not homework.",
        lessons: [
          {
            num: "1.1",
            title: "Naming Where You Actually Stand",
            durationMin: 9,
            objective: "the learner has a complete, honest snapshot of her current money situation in one place for the first time.",
            openingLine: "We're not judging the number today, we're just finally looking at it.",
            bullets: ["Open by naming the pattern: most people don't have a money problem, they have a \"won't look at it\" problem — avoidance costs more than any single bad decision does.", "Walk through gathering the four numbers that make up a real snapshot: total in checking/savings, total debt across every account, monthly income, and monthly essential expenses.", "Give permission for this to be uncomfortable the first time and reframe it as data collection, not a report card — a doctor needs the numbers before she can help, not judgment.", "Show where to actually find each number quickly (bank apps, a debt tracking app, or a simple manual list) so this doesn't turn into a multi-day project.", "Close with the snapshot fully filled in as the one deliverable of this lesson — everything else in the course builds from it."],
          },
          {
            num: "1.2",
            title: "Untangling Money From Self-Worth",
            durationMin: 8,
            objective: "the learner can name at least one inherited money belief that isn't serving her and one true statement to replace it with.",
            openingLine: "Your bank balance is not a report card on who you are — let's untangle those before we touch a single budget line.",
            bullets: ["Introduce the idea of \"money stories\" — beliefs picked up early, often not even consciously, from family, culture, or past hard times, that still drive decisions now.", "Give common examples to help viewers recognize their own: \"money is the reason my parents fought,\" \"wanting more than enough is greedy,\" \"I'm bad with money\" repeated so often it became identity.", "Teach the separation: a bank balance is a number, not a character reference — the goal of this course is skill-building, and skills can always be learned regardless of the current number.", "Offer a short reframing exercise: name the old belief, name where it likely came from, write one truer sentence to replace it.", "Close by connecting this directly to the rest of the course: every remaining lesson is the \"how,\" this lesson was the \"why now, and why it's safe to look.\""],
          },
        ],
        workbookItems: ["Money snapshot: fields for total savings, total debt (by account), monthly income, monthly essential expenses, and one blank line for \"how it feels to see this written down.\"", "Money story worksheet: \"A belief about money I inherited is ___,\" \"It probably came from ___,\" \"A truer sentence is ___.\""],
      },
      {
        num: 2,
        title: "The Calm Budget",
        framing: "most budgets fail because they're punitive. This module builds one that's built to actually survive a real month.",
        lessons: [
          {
            num: "2.1",
            title: "A Budget That Doesn't Feel Like a Punishment",
            durationMin: 10,
            objective: "the learner understands the difference between a restrictive budget and a calm one, and can name why past budgets didn't stick.",
            openingLine: "If your last budget felt like a punishment, that's not a you problem — it's a budget problem. Let's build a calmer one.",
            bullets: ["Open with the honest confession most viewers share: they've \"tried budgeting\" before and it lasted two weeks — name why, usually because it was built around deprivation instead of reality.", "Teach the calm-budget principle: a budget's job is to tell money where to go on purpose, not to forbid every non-essential purchase.", "Cover building in joy spending as a real line item from day one, not an afterthought or a guilty exception — a budget with zero room for a coffee or a treat is a budget that gets abandoned.", "Walk through the emotional side of past budget failures briefly, so this doesn't feel like a moral failing repeating itself.", "Set the tone for Module 2: the next lesson gives the actual system, this lesson just clears the ground so it can stick this time."],
          },
          {
            num: "2.2",
            title: "Building Your Three-Bucket System",
            durationMin: 13,
            objective: "the learner has her actual monthly income sorted into three working buckets, sized to her real numbers.",
            openingLine: "Three buckets, one system — let's sort every dollar so you always know where it's supposed to go.",
            bullets: ["Introduce the three-bucket framework: needs (non-negotiables — housing, food, minimum debt payments, utilities), future (savings and extra debt payoff), and life (everything that makes life feel good — the joy spending from 2.1).", "Give realistic starting percentages as a guide, not a rule (roughly 50/30/20 as a common starting split), and show how to adjust the split for her real numbers from the Module 1 snapshot rather than forcing an unrealistic ratio.", "Walk through actually assigning her real monthly expenses into the three buckets, line by line, using her snapshot from Lesson 1.1.", "Address the common snag directly: what to do when \"needs\" alone already exceeds what feels sustainable — this isn't a failure, it's information for Module 3 and 4 (debt and goals).", "Close with her three-bucket totals fully filled in as this lesson's deliverable, ready to track against for the rest of the course."],
          },
        ],
        workbookItems: ["Past-budget reflection: \"A budget I tried before was ___,\" \"It stopped working because ___.\"", "Three-bucket worksheet: monthly income at the top, then Needs / Future / Life columns with space to list each expense and its bucket, plus a running total per bucket.", "Joy-spending line: one line specifically protected for guilt-free spending, with an amount she commits to."],
      },
      {
        num: 3,
        title: "Debt, Decoded",
        framing: "debt is a math problem wearing an emotional costume. This module handles the math and the feelings, separately and in order.",
        lessons: [
          {
            num: "3.1",
            title: "Listing It Without Flinching",
            durationMin: 9,
            objective: "the learner has every debt she owes listed in one place with balance, interest rate, and minimum payment.",
            openingLine: "Let's get every single debt on one page — not to feel bad about it, just so we can finally make a plan against it.",
            bullets: ["Normalize the fact that most people have never seen all of their debt in one list — it's usually scattered across apps, mentally avoided, or only half-known.", "Walk through gathering the four fields per debt: who it's owed to, current balance, interest rate, and minimum monthly payment.", "Address avoidance directly and gently: it's common to not know the exact interest rate on a card — show her where to find it in five minutes rather than guessing.", "Reinforce the Module 1 tone: this list is data, not a verdict — the size of the list has no bearing on her worth or her ability to handle it, starting now.", "Close with the full list built, sorted for now by balance size (highest to lowest), setting up the payoff-method decision in 3.2."],
          },
          {
            num: "3.2",
            title: "Snowball or Avalanche: Choosing Your Method",
            durationMin: 10,
            objective: "the learner picks a debt payoff method and can explain why it fits her personality and numbers.",
            openingLine: "There's a mathematically perfect way to pay off debt, and there's the way you'll actually stick to — let's find yours.",
            bullets: ["Explain both payoff methods clearly: snowball (paying off the smallest balance first for quick emotional wins) and avalanche (paying off the highest interest rate first to save the most money).", "Give the honest tradeoff: avalanche is mathematically optimal, snowball is often psychologically sustainable — and sustainable beats optimal if optimal gets abandoned in month two.", "Use her list from 3.1 to model both methods side by side so she can see her own actual payoff order under each approach.", "Cover the \"extra payment\" concept: whatever amount from her Future bucket is going toward debt gets applied to the target debt while minimums are still paid on everything else.", "Have her commit to one method and mark her real payoff order in the workbook."],
          },
          {
            num: "3.3",
            title: "Talking to Creditors Like an Adult",
            durationMin: 11,
            objective: "the learner knows what to say and ask for when contacting a creditor about her debt.",
            openingLine: "Picking up the phone is scarier in your head than it is in real life — here's exactly what to say.",
            bullets: ["Normalize that calling a creditor feels intimidating but is a completely normal, common request that these departments field constantly.", "Cover the three most useful asks: a lower interest rate, a hardship or payment plan if she's struggling to meet minimums, and clarity on any fees she doesn't understand.", "Give an actual script structure to follow: state the account, state the ask plainly, and be ready to hear \"no\" and ask \"is there anything else you can offer\" before hanging up.", "Address negotiating from a place of calm confidence rather than apology — she's a customer asking a reasonable question, not asking for a favor she doesn't deserve.", "Close with her identifying one real creditor call she'll make this week, with her ask written out in advance."],
          },
        ],
        workbookItems: ["Full debt list: creditor, balance, interest rate, minimum payment — as many rows as needed.", "Method choice: snowball vs. avalanche comparison table pre-filled from her list, with her chosen method circled and her real payoff order written out.", "Creditor call script: account name, the ask, a backup ask, and a line for the date she plans to call."],
      },
      {
        num: 4,
        title: "The Safety Net",
        framing: "an emergency fund isn't about fear, it's about never having a bad week turn into a bad year. Two lessons, no fluff.",
        lessons: [
          {
            num: "4.1",
            title: "Your First $1,000",
            durationMin: 8,
            objective: "the learner has a concrete plan to reach her first $1,000 in savings.",
            openingLine: "One thousand dollars, held separately, changes how the whole rest of this plan feels — let's get you there first.",
            bullets: ["Make the case for the first $1,000 specifically: it's the amount that covers most small emergencies (a car repair, a vet bill) without reaching for a credit card, which is why it comes before debt payoff in priority.", "Address the \"but I have debt, shouldn't I pay that first\" question directly — a small starter fund prevents new debt while she works the plan from Module 3.", "Give three fast ways to find money for this: a one-time push (selling something, a tax refund, a bonus), a temporary pause on one Life-bucket expense, or a short sprint of extra hours/gig income.", "Show setting up a separate savings account for this money specifically, so it's not sitting in checking where it quietly gets spent.", "Have her set a target date for reaching $1,000 based on a realistic monthly contribution."],
          },
          {
            num: "4.2",
            title: "Sizing Your Real Emergency Fund",
            durationMin: 10,
            objective: "the learner knows her full emergency fund target based on her actual monthly needs.",
            openingLine: "Your real safety net isn't a number you copy from the internet — it's three to six months of YOUR needs. Let's find yours.",
            bullets: ["Once the first $1,000 is in place, teach the full emergency fund target: three to six months of her Needs-bucket expenses from Module 2, not her full income.", "Give guidance on where to land in that range: closer to three months for stable dual-income or salaried situations, closer to six for freelance, commission, or single-income households.", "Address the \"this feels impossible\" reaction directly: this is a multi-month or multi-year goal by design, not something to build overnight, and Module 6 will turn it into a real timeline.", "Cover where to keep this money (a high-yield savings account, separate from spending and separate from the debt payoff plan) so it stays both safe and slightly growing.", "Close by having her calculate her personal three-month and six-month numbers and mark where on that range she's aiming."],
          },
        ],
        workbookItems: ["First $1,000 plan: current amount saved, monthly contribution, target date, and one funding idea from the lesson she'll actually use.", "Full fund calculator: monthly Needs total (from Module 2) × 3 and × 6, with a line to circle her personal target and where she'll keep it."],
      },
      {
        num: 5,
        title: "Saving on Purpose",
        framing: "saving that depends on willpower fails. This module removes willpower from the equation entirely.",
        lessons: [
          {
            num: "5.1",
            title: "Automating So Willpower Isn't Required",
            durationMin: 9,
            objective: "the learner has at least one automatic transfer set up so saving happens without a monthly decision.",
            openingLine: "The goal isn't more willpower, it's needing less of it — let's automate this so it just happens.",
            bullets: ["Open with the core principle: the households that save consistently aren't more disciplined, they've just made saving automatic instead of a decision they have to make and win every single month.", "Walk through setting up an automatic transfer timed to payday, for an amount pulled straight from her Future bucket in Module 2.", "Cover starting small if the ideal amount feels scary — a $25 automatic transfer that actually happens beats a $200 planned transfer that gets skipped.", "Address the psychological shift: once it's automatic, the money is \"already saved\" before she sees it in checking, removing the temptation to spend it first.", "Have her actually set up the transfer during the lesson, not just plan to later."],
          },
          {
            num: "5.2",
            title: "Sinking Funds for the Life You Actually Want",
            durationMin: 10,
            objective: "the learner has at least two sinking funds set up for specific, planned future expenses.",
            openingLine: "The 'surprise' expenses every year aren't actually surprises — let's plan for them on purpose.",
            bullets: ["Introduce sinking funds as the tool that prevents \"surprise\" expenses that aren't actually surprises — holiday spending, an annual insurance bill, a trip, a wedding gift season.", "Teach the simple math: take the total cost, divide by the number of months until it's due, and that's the monthly amount to set aside.", "Give common sinking fund categories to spark her own list: holidays/gifts, car maintenance, annual subscriptions or insurance, travel, a personal goal purchase.", "Show keeping sinking funds separate from the emergency fund — the emergency fund is for the unplanned, sinking funds are for the fully planned.", "Have her set up two real sinking funds with target amounts and monthly contributions before moving to Module 6."],
          },
        ],
        workbookItems: ["Automation setup: amount, source account, destination account, transfer date — confirmed with a checkbox once actually set up.", "Sinking fund planner: a table for at least 3 funds with columns for total cost, months until needed, and monthly contribution."],
      },
      {
        num: 6,
        title: "Goals With a Deadline",
        framing: "closing the course by turning everything built so far into one real map with real dates, so \"someday\" becomes a plan.",
        lessons: [
          {
            num: "6.1",
            title: "Turning Dreams Into Numbers",
            durationMin: 10,
            objective: "the learner has translated her top 1–3 money goals into specific dollar amounts and dates.",
            openingLine: "A dream with a date and a number on it is just a goal — let's put both on paper.",
            bullets: ["Open by naming the gap between a wish (\"I want to feel financially secure\") and a goal (a specific number by a specific date) — this lesson closes that gap.", "Walk through picking her top one to three goals for the coming year, pulling from anything mentioned earlier in the course (finishing the emergency fund, paying off a specific debt, a big purchase, starting an investment habit).", "Teach turning each into the same simple formula: total amount needed, divided by months available, equals the monthly amount required.", "Address realism directly: if the required monthly amount doesn't fit her three-bucket budget from Module 2, the goal needs a longer timeline or the budget needs revisiting — both are fine, guessing isn't.", "Have her write all chosen goals in the exact number-and-date format before the final lesson."],
          },
          {
            num: "6.2",
            title: "Your One-Year Money Map",
            durationMin: 9,
            objective: "the learner leaves the course with one visual, month-by-month map connecting everything she's built.",
            openingLine: "Let's put the whole year on one page — everything you've built in this course, connected into a single map.",
            bullets: ["Bring together every piece from the course into one page: current snapshot, three-bucket budget, debt payoff order, emergency fund target, sinking funds, and the goals from 6.1.", "Walk through filling in a twelve-month grid with key milestones per month (e.g., \"month 3: emergency fund hits $1,000,\" \"month 7: card X paid off\").", "Address the emotional close of the course: this map will need adjusting as real life happens, and that's not failure — it's what a living plan does.", "Give a simple monthly check-in habit to keep the map current (same five-minute spirit as the numbers review in the flagship course), so this doesn't become another document that gets made once and forgotten.", "Close by connecting back to Module 1: she started by finally looking at the number without flinching, and she's ending with a full map she built herself."],
          },
        ],
        workbookItems: ["Goals worksheet: up to 3 goals, each with total amount, target date, and required monthly amount.", "One-year money map: a 12-month grid with a line per month for the one milestone she's aiming for.", "Monthly check-in template: a simple repeatable box (date, what's on track, what needs adjusting) to photocopy or reuse each month after the course ends."],
      },
    ],
  },
  {
    id: "c3",
    title: "AI for the Modern Woman",
    promise: "by the end of this course, a learner has a working AI toolkit she actually uses — for planning her week, writing content in her own voice, handling the admin she dreads, and running her household — plus a clear sense of where AI stops and her own judgment has to take over.",
    who: "a woman who has heard \"just use AI for that\" a hundred times, tried ChatGPT once, got a generic answer, and closed the tab — this course is the difference between poking at it and actually using it.",
    price: 129,
    tier: 'single',
    status: "draft",
    slug: "ai-for-the-modern-woman",
    modules: [
      {
        num: 1,
        title: "Getting Comfortable With AI",
        framing: "most of the hesitation here isn't about capability, it's about not knowing where to start. This module removes the intimidation before asking her to do anything.",
        lessons: [
          {
            num: "1.1",
            title: "What These Tools Actually Do",
            durationMin: 9,
            objective: "the learner can explain, in plain language, what an AI chat tool is actually doing and where its limits are.",
            openingLine: "Let's demystify this in nine minutes — no jargon, just what it actually does and doesn't do.",
            bullets: ["Open by naming the two extremes people land on — \"it's magic, it knows everything\" or \"it's useless, it gave me a weird answer once\" — and reset expectations to the middle, honest truth.", "Explain simply what these tools are good at (organizing, drafting, brainstorming, summarizing, explaining) versus what they get wrong (specific facts, anything time-sensitive, anything requiring real judgment about her actual life).", "Teach the single most useful mental model: it's a very well-read assistant who's never met her and needs to be told everything relevant, every time — it doesn't remember unless she tells it to.", "Address the guilt/fear angle directly and briefly: using AI isn't cheating or lazy, it's using a tool, the same way a calculator didn't make people bad at math judgment.", "Close with a live, no-pressure first prompt she can try during the lesson just to get a feel for the interface."],
          },
          {
            num: "1.2",
            title: "Setting Up Your AI Toolkit",
            durationMin: 10,
            objective: "the learner has one AI tool set up and ready to use, with an account and the basics configured.",
            openingLine: "Fifteen minutes from now, you'll have this set up and ready — let's do it together, live.",
            bullets: ["Recommend one clear starting tool rather than overwhelming with five options — pick based on what's genuinely easiest for a first-timer, and mention that the skills transfer to any tool later.", "Walk through account setup step by step: creating an account, understanding the free vs. paid tiers, and what's actually worth paying for at this stage (usually: nothing yet, start free).", "Cover the interface basics: where to type, how to start a \"new chat\" versus continuing one, and why starting fresh chats for different topics keeps things cleaner.", "Introduce the idea of saving good prompts she'll reuse (a simple running note is enough — no special tool required).", "Close with her toolkit fully set up and one practice conversation started, ready for Module 2's real use cases."],
          },
        ],
        workbookItems: ["Mental model recap: a one-line fill-in — \"The one thing I need to remember is: AI is ___, not ___.\"", "Setup checklist: account created, free tier understood, first practice chat started — checkboxes for each.", "Prompt journal starter page: a simple two-column table (prompt / how it went) to start collecting what works for her."],
      },
      {
        num: 2,
        title: "Reclaiming Your Calendar",
        framing: "the fastest, most satisfying win in the whole course — getting a week's worth of planning done in minutes instead of an hour of staring at a blank page.",
        lessons: [
          {
            num: "2.1",
            title: "Prompting a Weekly Plan in Minutes",
            durationMin: 11,
            objective: "the learner can generate a usable weekly plan by giving AI the right context.",
            openingLine: "Give it the right details and this turns into a real planning assistant — let's build your week right now.",
            bullets: ["Open with the common failure mode: typing \"help me plan my week\" and getting a generic, useless answer — then show why (not enough context given).", "Teach the context formula: what's already fixed on the calendar, top 3 priorities for the week, and any constraints (energy levels, specific days that are tighter than others).", "Model a full prompt live, then show the output and how to react to it — treating the AI's plan as a rough draft to edit, not a final answer to accept blindly.", "Cover asking follow-up questions to refine it (\"move my deep work to mornings,\" \"I forgot I have an appointment Tuesday\") rather than starting over from scratch each time.", "Have her run this for her actual upcoming week during the lesson."],
          },
          {
            num: "2.2",
            title: "Building Your Personal Assistant Prompt",
            durationMin: 10,
            objective: "the learner has a saved, reusable \"personal assistant\" prompt template she can use every week going forward.",
            openingLine: "Let's write this once, so every future week only takes you thirty seconds to plan.",
            bullets: ["Introduce the idea of a template prompt: instead of rebuilding context every time, she writes it once and reuses it with small updates.", "Walk through building the template together: a fixed opening describing her role/life context, a section for that week's specific priorities, and a closing instruction on the format she wants back (a simple list, a table, time-blocked).", "Show saving this template somewhere easy to grab (notes app, a doc) so using it becomes a five-second copy-paste, not a rewrite.", "Address personalization: everyone's template should look a little different based on what actually matters to her (a business owner's looks different from a stay-at-home parent's).", "Close with her final template saved and ready to reuse starting next week."],
          },
        ],
        workbookItems: ["Weekly plan prompt worksheet: fixed calendar items, top 3 priorities, constraints — the exact fields to fill in before prompting.", "Personal assistant template: a fill-in-the-blank template structure (role/context, this week's priorities, desired output format) to copy into her AI tool going forward."],
      },
      {
        num: 3,
        title: "Content Without the Burnout",
        framing: "not \"let AI write your content\" but \"let AI clear the blank page so your real voice can show up faster.\"",
        lessons: [
          {
            num: "3.1",
            title: "Turning One Idea Into a Week of Posts",
            durationMin: 12,
            objective: "the learner can take a single idea and generate a week's worth of content angles from it.",
            openingLine: "One idea, five posts — let's stop staring at a blank content calendar for good.",
            bullets: ["Open with the real bottleneck in content creation: it's rarely a lack of ideas, it's turning one idea into enough different angles to post about all week without repeating herself.", "Teach the \"one idea, five angles\" prompt approach: feeding AI one core idea or story and asking for it back as a tip post, a personal story post, a myth-busting post, a question/engagement post, and a behind-the-scenes post.", "Model this live with a realistic example idea, showing the range of outputs from one input.", "Cover treating every output as a rough draft — the next lesson (3.2) is specifically about making sure it doesn't sound robotic once she edits it.", "Have her run this process on one of her own real content ideas before the lesson ends."],
          },
          {
            num: "3.2",
            title: "Finding Your Voice So It Doesn't Sound Like a Robot",
            durationMin: 9,
            objective: "the learner can reliably edit AI-generated drafts so they sound like her, not like generic AI copy.",
            openingLine: "Here's exactly how to spot the robot voice — and three small edits that make any draft sound like you.",
            bullets: ["Name the tell-tale signs of \"AI voice\" directly so she can spot it: overly formal transitions, excessive emoji or hashtags, phrases that sound like nobody actually talks, a lack of specific personal detail.", "Teach the fix: feeding AI a sample of her own past writing or captions and asking it to match that tone specifically, rather than accepting generic default tone.", "Give a simple personal edit pass to always do: read it out loud, and change any sentence she wouldn't actually say to a friend.", "Cover adding one true personal detail to every AI-drafted post — a specific example, a real number, an actual moment — since specificity is what generic AI text is missing.", "Close by having her take one draft from Lesson 3.1 through this full \"make it sound like me\" process."],
          },
        ],
        workbookItems: ["One idea, five angles worksheet: her core idea at the top, five labeled slots for each angle's draft.", "Voice-check pass: a short checklist — read aloud, replace robotic phrases, add one true detail — applied to one real post before posting it."],
      },
      {
        num: 4,
        title: "The Admin You Hate, Automated",
        framing: "the unglamorous, high-relief part of the course — the tasks she's been dreading get a system.",
        lessons: [
          {
            num: "4.1",
            title: "Email and Inbox Triage",
            durationMin: 10,
            objective: "the learner has a repeatable AI-assisted process for clearing a backlogged inbox.",
            openingLine: "Let's finally clear that inbox — with AI doing the first draft and you doing the thirty-second edit.",
            bullets: ["Open by naming the real cost of an overflowing inbox: not just the mess, but the mental weight of every unanswered message sitting there.", "Teach a triage prompt approach: pasting in a batch of email content (with any sensitive info removed) and asking AI to summarize what each needs and draft short reply options.", "Cover using AI to draft replies she then reviews and personalizes rather than sending untouched — speed without losing her own voice or accuracy.", "Address the privacy note directly and clearly: never paste in truly sensitive personal, financial, or client information — this tool is for drafting language, not for handling private data.", "Have her run this process on her actual current inbox backlog during the lesson."],
          },
          {
            num: "4.2",
            title: "Templates for the Messages You Send Weekly",
            durationMin: 9,
            objective: "the learner has a small library of message templates for the emails/texts she sends most often.",
            openingLine: "You're probably retyping the same five messages every week — let's turn them into templates, once, for good.",
            bullets: ["Introduce the idea: most people retype some version of the same 5–8 messages constantly (a follow-up, a scheduling message, a polite decline, a check-in) — these deserve permanent templates.", "Walk through identifying her own most repeated message types by scanning her sent folder or just thinking through the week.", "Model generating a clean, warm, reusable template for each one with AI, then personalizing the tone to sound like her.", "Cover storing these somewhere she'll actually find them again (notes app, saved email drafts) so the system gets used, not built once and forgotten.", "Close with at least three real templates finished and saved."],
          },
        ],
        workbookItems: ["Inbox triage log: a simple table (sender/topic, what's needed, drafted reply status) to run through a real backlog.", "Message template library: a table with columns for message type, when it's used, and the finished template text — with room for at least 5 entries."],
      },
      {
        num: 5,
        title: "AI for the Home and Family",
        framing: "taking the same skills out of \"work mode\" and into the parts of life that eat the most invisible mental energy.",
        lessons: [
          {
            num: "5.1",
            title: "Meal Planning and Grocery Lists in Minutes",
            durationMin: 10,
            objective: "the learner can generate a full week of meals and a matching grocery list using AI.",
            openingLine: "What's for dinner this week? Let's get that answered for all seven nights in the next ten minutes.",
            bullets: ["Open by naming meal planning as one of the most draining recurring decisions in a household — not because cooking is hard, but because deciding what to cook, every day, is exhausting.", "Teach the context-rich prompt: household size, dietary needs or preferences, roughly how much time is available to cook on weeknights versus weekends, and what's already in the pantry if relevant.", "Model generating a full week of dinners plus a consolidated grocery list organized by store section.", "Cover quick follow-up adjustments (swap a meal, account for a busy Tuesday, use up something about to expire) rather than regenerating the whole week.", "Have her generate her actual meal plan for the coming week during the lesson."],
          },
          {
            num: "5.2",
            title: "Organizing Family Schedules and To-Dos",
            durationMin: 9,
            objective: "the learner has a system for using AI to untangle a busy household's schedule and task list.",
            openingLine: "You shouldn't have to hold the whole family's schedule in your head alone — let's get some of that weight off you.",
            bullets: ["Open with the mental load reality: she's often the one holding every family member's schedule in her head, and that invisible tracking is exhausting even when nothing's technically going wrong.", "Teach feeding AI everyone's fixed commitments and open tasks to get back an organized view: what's happening when, what needs to be done by when, and any scheduling conflicts flagged.", "Cover using it for specific recurring headaches: packing lists for trips, holiday planning, coordinating multiple kids' activities, or household project checklists.", "Address the boundary clearly: AI can organize the information she gives it, but she's still the one deciding priorities — it's a mental-load reducer, not a replacement for her judgment about her own family.", "Close with her building one real organizing system (a schedule view or a checklist) for something actually on her plate this month."],
          },
        ],
        workbookItems: ["Meal plan worksheet: household size, dietary notes, time available, pantry staples — the fields to fill in before prompting, plus space to paste her finished week's plan.", "Family organizer: a space to list fixed commitments and open to-dos for the household, plus one specific upcoming event (trip, holiday, project) to build a checklist for."],
      },
      {
        num: 6,
        title: "Guardrails and Good Judgment",
        framing: "closing the course with the most important lesson — knowing where the tool ends and she begins.",
        lessons: [
          {
            num: "6.1",
            title: "What Not to Hand Over to AI",
            durationMin: 9,
            objective: "the learner can name specific categories of decisions and information she will keep fully in her own hands.",
            openingLine: "This tool is here to save you time, never to make your calls for you — let's draw that line clearly.",
            bullets: ["Open by reinforcing that everything in this course has been about removing drudgery, never about removing her judgment — this lesson draws that line explicitly.", "Cover categories to never fully hand over: final decisions involving other people's wellbeing (medical, legal, financial decisions for herself or family), anything requiring truly private or sensitive information, and any message or decision where getting it wrong has real consequences.", "Teach the \"draft, never decide\" rule as a simple heuristic she can apply to any new use case that comes up after the course ends.", "Give a few real examples of AI getting confidently wrong answers, so she leaves appropriately skeptical rather than over-trusting.", "Close by having her write her own personal list of \"always mine to decide\" categories."],
          },
          {
            num: "6.2",
            title: "Fact-Checking and Staying You",
            durationMin: 8,
            objective: "the learner has a habit of verifying anything factual before using it, and feels confident her AI-assisted output still sounds like her.",
            openingLine: "Last thing, and it matters most: always double-check the facts, and always make sure the final version still sounds like you.",
            bullets: ["Teach a simple rule: anything presented as a specific fact, statistic, date, or claim gets independently verified before she repeats it anywhere public.", "Cover quick verification habits: a fast search to confirm anything factual, and being especially cautious with anything time-sensitive since these tools can be out of date.", "Revisit the \"sounding like me\" work from Module 3 as an ongoing habit, not a one-time lesson — a quick gut-check before posting or sending anything AI-assisted.", "Close the course by reflecting on the shift from Lesson 1.1's hesitation to a working toolkit she now owns, and encourage her to keep a running list of new use cases as she discovers them in daily life.", "End with an invitation to revisit this course's workbook anytime as a reference, not just a one-time watch-through."],
          },
        ],
        workbookItems: ["\"Always mine to decide\" list: a space to write out her own personal boundaries for what she'll never fully hand over.", "Fact-check habit card: a short repeatable checklist — verify facts independently, double-check anything time-sensitive, read the final version aloud to confirm it sounds like her.", "Course close-out: \"the use case I'm most excited to try this week is ___.\""],
      },
    ],
  },
  {
    id: "c4",
    title: "Personal Brand Glow-Up",
    promise: "by the end of this course, a learner has a clearly named personal brand, a simple visual identity and bio, a content rhythm she can actually sustain, a real strategy for growing an audience that trusts her, a path from free content to paid offers, and boundaries that keep the whole thing sustainable long-term.",
    who: "a woman with something to say and an audience she wants to grow, who has been posting inconsistently without a strategy and wants her online presence to feel like her — and eventually pay her.",
    price: 149,
    tier: 'single',
    status: "draft",
    slug: "personal-brand-glow-up",
    modules: [
      {
        num: 1,
        title: "Your Brand, Named",
        framing: "a personal brand isn't a logo, it's clarity about who she helps and why she's the one to do it. This module is entirely clarity work before anything gets built.",
        lessons: [
          {
            num: "1.1",
            title: "Getting Clear on Who You Help",
            durationMin: 10,
            objective: "the learner can state clearly who her content and brand are for, and what specific transformation or value she offers them.",
            openingLine: "A brand isn't a topic, it's a promise to a specific person — let's find yours.",
            bullets: ["Open with the most common brand mistake: trying to appeal to everyone, which in practice makes content forgettable to everyone.", "Teach the difference between a topic (\"I post about wellness\") and a brand (\"I help burnt-out moms find fifteen minutes of calm a day\") — the second gives every future piece of content a job to do.", "Walk through three questions to find this: what do people already come to her for advice about, what does she wish she'd been told earlier in her own journey, and what perspective does she hold that feels a little different from the crowd.", "Address the fear of narrowing directly: a specific brand attracts the RIGHT people faster, it doesn't shut out everyone else from ever finding her.", "Close with her writing a first-draft version of who she helps and how, to be refined into her signature story next."],
          },
          {
            num: "1.2",
            title: "Finding Your Signature Story",
            durationMin: 9,
            objective: "the learner has identified and outlined the personal story that will anchor her brand's credibility and connection.",
            openingLine: "Every brand people trust has one story underneath it — let's find and shape yours.",
            bullets: ["Introduce the idea of a signature story: the one story she'll tell (and retell, in different forms) that explains why she does this and why she's credible on the topic.", "Teach the simple three-part shape: where she started (the struggle or the moment things weren't working), what changed (the turning point or what she learned), and where she is now (and why that qualifies her to help others with it).", "Give the permission slip that the story doesn't need to be dramatic — an honest, specific, relatable story beats an exaggerated one every time.", "Cover how this story will get reused: a version for her bio, a longer version for a pinned post or \"about\" page, and shorter fragments that show up naturally in regular content.", "Close with a full first draft of her signature story written out in the three-part shape."],
          },
        ],
        workbookItems: ["Clarity worksheet: \"I help ___ with ___,\" plus answers to the three questions (what people already ask her, what she wishes she'd known sooner, her different perspective).", "Signature story outline: three labeled sections — where I started, what changed, where I am now — with space to draft each."],
      },
      {
        num: 2,
        title: "The Look and Feel",
        framing: "visual identity and bio, kept simple on purpose — this is not a full brand design course, it's \"good enough to look intentional, fast.\"",
        lessons: [
          {
            num: "2.1",
            title: "Building a Simple Visual Identity",
            durationMin: 11,
            objective: "the learner has chosen a small, consistent set of colors, fonts, and photo style to use across her content.",
            openingLine: "You don't need a full brand book, you need three consistent choices — let's pick them today.",
            bullets: ["Open by reframing the goal: not a full brand book, just enough visual consistency that her content is recognizable at a glance before anyone reads a word.", "Walk through picking three core pieces: a small color palette (2–3 colors), one or two fonts for anything she designs (captions, graphics), and a consistent photo/video style (lighting, setting, editing look).", "Give a fast decision method for anyone overwhelmed by choice: pick based on what already feels like her (her closet, her home, colors she's drawn to) rather than researching endlessly.", "Show setting these up once in a simple design tool as a reusable template/brand kit, so future content pulls from it instead of starting from scratch.", "Close with her three choices locked in and saved somewhere she'll actually reuse them."],
          },
          {
            num: "2.2",
            title: "Writing a Bio That Actually Sounds Like You",
            durationMin: 8,
            objective: "the learner has a finished bio for her main platform that clearly states who she helps and sounds like her.",
            openingLine: "Your bio has about three seconds to do its job — let's make every word earn its place.",
            bullets: ["Give the simple bio formula: who she helps, how she helps them, and a personal or personality-driven line that makes her sound like a person, not a brochure.", "Model turning the \"I help ___ with ___\" line from Module 1 directly into the first part of the bio.", "Cover the common bio mistakes to avoid: too vague (\"passionate about growth\"), too crowded (trying to list everything she does), missing any way for someone to know what to do next (a clear call to action or link).", "Teach a quick voice check: read it out loud — if it sounds like a press release instead of her, rewrite the personality line until it doesn't.", "Close with a finished, ready-to-publish bio."],
          },
        ],
        workbookItems: ["Visual identity board: fields for 2–3 brand colors (with hex codes if known), 1–2 fonts, and 2–3 words describing her photo/content style.", "Bio builder: the formula broken into three fill-in lines (who I help, how I help, personality line), plus a final assembled draft."],
      },
      {
        num: 3,
        title: "Showing Up With Consistency",
        framing: "consistency beats intensity. This module picks a sustainable lane instead of trying to be everywhere.",
        lessons: [
          {
            num: "3.1",
            title: "Choosing Your Two Platforms",
            durationMin: 9,
            objective: "the learner has chosen one primary and one secondary platform to focus her energy on.",
            openingLine: "Pick two, not five — let's choose where you're actually going to show up.",
            bullets: ["Open with the trap of trying to show up everywhere at once, which usually results in showing up nowhere consistently or well.", "Teach the decision factors: where does her ideal audience (from Module 1) actually spend time, and which platform's format fits her natural strengths (writing, talking on camera, visuals).", "Give a simple primary/secondary structure: one platform gets the real strategy and consistent effort, the second gets repurposed content from the first with minimal extra work.", "Address platform-hopping anxiety directly: choosing two now doesn't mean forever, it means enough focus to actually build momentum before reconsidering.", "Close with her two platforms chosen and written down as a commitment for the next 90 days."],
          },
          {
            num: "3.2",
            title: "A Content Rhythm You Can Actually Keep",
            durationMin: 10,
            objective: "the learner has a realistic weekly posting rhythm she's confident she can sustain for months, not days.",
            openingLine: "Consistency isn't about posting every day, it's about picking a rhythm you'll still be doing in six months.",
            bullets: ["Open with the honest question: not \"what's the ideal posting frequency\" but \"what frequency will I actually keep up in a busy, real week.\"", "Teach starting smaller than feels impressive — three intentional posts a week beats a daily posting streak that burns out by week three.", "Cover building in repurposing from the start: one piece of primary-platform content becomes 2–3 pieces for the secondary platform with minimal extra effort.", "Give a simple weekly content skeleton to adapt (similar spirit to the flagship course's three-post rhythm): one value/teaching post, one personal/story post, one engagement or conversation-starter post.", "Close with her actual weekly rhythm written down, sized to a realistic week rather than an aspirational one."],
          },
        ],
        workbookItems: ["Platform decision worksheet: primary platform and why, secondary platform and why, 90-day commitment note.", "Weekly rhythm planner: days of the week with post type slots (value, personal, engagement) sized to a realistic number per week."],
      },
      {
        num: 4,
        title: "Growing an Audience That Trusts You",
        framing: "growth reframed away from vanity numbers and toward the kind of audience that actually engages and eventually buys.",
        lessons: [
          {
            num: "4.1",
            title: "Turning Followers Into Community",
            durationMin: 10,
            objective: "the learner has at least two concrete tactics to turn passive followers into an engaged, familiar community.",
            openingLine: "Followers scroll past you, a community shows up for you — let's build the second one.",
            bullets: ["Open by naming the real goal shift: follower count is a vanity number, a community that recognizes her and talks back is the number that actually matters for everything downstream (trust, eventually sales).", "Teach the difference between broadcasting and conversing — regularly asking questions, responding to comments personally, and referencing her own audience's responses in future content.", "Give specific tactics: a recurring content series or format people start to expect and look for, direct replies to comments/DMs on a regular cadence, and occasionally featuring or thanking specific community members.", "Address the time-management reality: this doesn't require being available 24/7, it requires consistent, scheduled pockets of real engagement rather than sporadic bursts.", "Close with her choosing two tactics to actually implement starting this week."],
          },
          {
            num: "4.2",
            title: "Engagement Without Losing Your Evenings",
            durationMin: 8,
            objective: "the learner has a bounded, sustainable daily/weekly engagement routine.",
            openingLine: "Let's put real boundaries around engagement so it fits into your life instead of eating your evenings.",
            bullets: ["Open by naming the burnout trap directly: engagement matters, but unlimited scrolling and replying \"whenever\" eats entire evenings and still doesn't feel like enough.", "Teach time-boxing engagement: two or three set windows a day (e.g., morning coffee, lunch, one evening check) rather than being reachable constantly.", "Cover batching replies similarly to batching content — clearing comments and DMs in a focused sprint rather than a constant background task.", "Give permission to not respond to everything instantly, and to mute notifications outside her chosen windows without guilt.", "Close with her own bounded engagement schedule written down, sized to protect her actual evenings."],
          },
        ],
        workbookItems: ["Community tactics worksheet: a list of options with two circled as this week's commitment, plus a note on how she'll track whether they're working.", "Engagement schedule: a simple daily/weekly time-box template (e.g., three named windows) to keep engagement contained."],
      },
      {
        num: 5,
        title: "Positioning to Get Paid",
        framing: "the moment the brand starts converting into income — moving from all-free content to a real offer, without a jarring, salesy pivot.",
        lessons: [
          {
            num: "5.1",
            title: "From Free Value to Paid Offers",
            durationMin: 11,
            objective: "the learner understands how to introduce a paid offer to an audience built on free content without it feeling like a bait-and-switch.",
            openingLine: "Free content built the trust — now let's talk about how to introduce what's next without breaking it.",
            bullets: ["Open by naming the fear directly: many creators avoid ever mentioning a paid offer because they're afraid of \"ruining\" the free, trusted relationship — show why the opposite is usually true when done well.", "Teach the free-to-paid ladder: free content teaches the \"what\" and \"why,\" a paid offer delivers the \"how\" in more depth, structure, or directly done for/with them.", "If she's completed *Build Your Digital Empire*, connect directly to her existing offer here as the natural next step; if not, cover the simplest possible starting offer (a low-cost digital product, a single coaching call) to introduce first.", "Give language for introducing an offer for the first time without it feeling like a pivot: naming that people have been asking for more, and framing the offer as the deeper version of what she's already been giving away.", "Close with her drafting one sentence that introduces her offer to her existing audience for the first time."],
          },
          {
            num: "5.2",
            title: "Pricing Your Presence",
            durationMin: 9,
            objective: "the learner sets a price for her offer or her time that reflects her actual value, not her comfort with charging.",
            openingLine: "Let's price this based on your value, not your fear of the comment section.",
            bullets: ["Open with the pattern from the flagship course, applied here to personal brand work specifically: creators tend to underprice out of fear the audience \"won't pay,\" especially when the audience feels like friends.", "Teach three pricing anchors specific to a personal-brand-driven offer: what she'd need per sale to make the effort worthwhile, what comparable creators in her space charge, and what her audience size and engagement level can realistically support.", "Address the audience-size myth directly: a smaller, highly engaged, trusting audience often converts and pays better than a much larger, passive one.", "Cover the option to start slightly lower for an early cohort or founding round, with a plan to raise the price as she gains testimonials and proof — a strategy, not a permanent underpricing.", "Close with a committed price and the reasoning behind it written down."],
          },
        ],
        workbookItems: ["Free-to-paid ladder: what her free content currently teaches, and what the paid offer adds beyond it.", "Offer introduction draft: the one sentence she'll use to introduce her offer to her existing audience for the first time.", "Pricing worksheet: three anchors (worth-it price, comparable creator pricing, audience-supported price) with her final price circled."],
      },
      {
        num: 6,
        title: "Protecting Your Peace",
        framing: "closing the course with sustainability — the brand only matters if she's still enjoying building it a year from now.",
        lessons: [
          {
            num: "6.1",
            title: "Handling Criticism and Comparison",
            durationMin: 9,
            objective: "the learner has a personal plan for handling negative comments and comparison to other creators without it derailing her.",
            openingLine: "If you're visible, someone eventually has an opinion — let's build your plan for that day before it happens.",
            bullets: ["Open by normalizing that any visible personal brand eventually draws some criticism and constant exposure to other people's highlight reels — this isn't a sign she's doing something wrong, it's a predictable part of the work.", "Teach the useful-versus-noise filter for criticism: is this specific, constructive feedback from someone she respects, or is it vague negativity with nothing actionable in it — respond to the first, mute/ignore the second.", "Cover a practical comparison reset: unfollowing or muting accounts that consistently trigger comparison spirals, without guilt, and limiting how much time is spent consuming others' content versus creating her own.", "Give a short personal script for the moment a harsh comment lands: a pause before responding (or not responding at all), and one grounding question — \"would I take this feedback from a stranger on the street?\"", "Close with her writing her own personal plan for the next time criticism or comparison hits."],
          },
          {
            num: "6.2",
            title: "Boundaries for a Sustainable Brand",
            durationMin: 8,
            objective: "the learner has explicit personal boundaries around her brand that she can return to when things start feeling unsustainable.",
            openingLine: "Last lesson: let's make sure this brand serves your life, not the other way around.",
            bullets: ["Open by connecting back to Module 4's engagement boundaries and widening the lens to the whole brand: what does \"sustainable for years\" actually require versus what's just intense for a launch season.", "Cover boundary categories to consider: what she will and won't share publicly, how much unpaid time she'll give to free requests or collaborations, and built-in breaks or lower-output seasons without guilt.", "Address the identity question directly: her brand is something she built and can adjust, not something that owns her — permission to evolve it, slow it down, or change direction later without that being a failure.", "Close the course by connecting all six modules together: from naming who she helps, to showing up consistently, to eventually getting paid for it — all held together by boundaries that make it sustainable rather than something she'll need to recover from.", "End with an invitation to revisit the workbook in three months to check whether her boundaries and rhythm still fit her real life."],
          },
        ],
        workbookItems: ["Criticism response plan: the filter question (useful feedback vs. noise), and her personal grounding script for a hard moment.", "Boundary list: what I will share, what I won't, how much unpaid time I'll give, and one built-in break I'm committing to.", "Course close-out: \"the part of this brand I'm most proud of so far is ___,\" with a note to revisit this workbook in 3 months."],
      },
    ],
  },
];
