#!/usr/bin/env python3
"""
Export the parsed curriculum JSON (produced by parse_curriculum.py) into a single
TypeScript data module the Expo app can import directly.

Usage:
    python3 export_seed_ts.py <json_dir> <out_ts_path>

Example:
    python3 export_seed_ts.py ../output/json ../../mobile-app/src/data/seed.ts

This is what wires the content pipeline to the app: parse_curriculum.py turns the
course-writer's markdown into structured JSON, this script turns that JSON into the
typed seed data the app ships with. Re-run both any time the curriculum docs change.
"""
import json
import os
import re
import sys

COURSE_IDS = ["c1", "c2", "c3", "c4"]
STATUS_BY_ID = {"c1": "published", "c2": "draft", "c3": "draft", "c4": "draft"}


def slugify(s):
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def js_str(s):
    return json.dumps(s or "", ensure_ascii=False)


def duration_label(minutes):
    return f"{minutes} min"


def build_course(cid, data):
    modules = []
    for m in data["modules"]:
        lessons = []
        for l in m["lessons"]:
            lessons.append({
                "num": l["num"],
                "title": l["title"],
                "durationMin": l["duration"],
                "objective": l["objective"],
                "openingLine": l["opening_line"],
                "bullets": l["bullets"],
            })
        modules.append({
            "num": m["num"],
            "title": m["title"],
            "framing": m["framing"],
            "lessons": lessons,
            "workbookItems": m["workbook_items"],
        })

    return {
        "id": cid,
        "title": data["title"],
        "tagline": data["promise"].split(" — ")[0][:0] or None,  # placeholder, unused
        "promise": data["promise"],
        "who": data["who"],
        "price": data["price"],
        "tier": data["tier"],
        "status": STATUS_BY_ID.get(cid, "draft"),
        "slug": slugify(data["title"]),
        "modules": modules,
    }


def ts_escape(s):
    return json.dumps(s if s is not None else "", ensure_ascii=False)


def emit(courses):
    lines = []
    lines.append("// AUTO-GENERATED by content-pipeline/scripts/export_seed_ts.py — do not hand-edit.")
    lines.append("// Regenerate with: python3 export_seed_ts.py <json_dir> <out_ts_path>")
    lines.append("// Source of truth is the curriculum markdown in content-pipeline/curriculum-source/.")
    lines.append("")
    lines.append("export type LessonSeed = {")
    lines.append("  num: string;")
    lines.append("  title: string;")
    lines.append("  durationMin: number;")
    lines.append("  objective: string;")
    lines.append("  openingLine: string;")
    lines.append("  bullets: string[];")
    lines.append("};")
    lines.append("")
    lines.append("export type ModuleSeed = {")
    lines.append("  num: number;")
    lines.append("  title: string;")
    lines.append("  framing: string;")
    lines.append("  lessons: LessonSeed[];")
    lines.append("  workbookItems: string[];")
    lines.append("};")
    lines.append("")
    lines.append("export type CourseStatus = 'draft' | 'published' | 'archived';")
    lines.append("export type CourseTier = 'single' | 'bundle' | 'full_access';")
    lines.append("")
    lines.append("export type CourseSeed = {")
    lines.append("  id: string;")
    lines.append("  title: string;")
    lines.append("  promise: string;")
    lines.append("  who: string;")
    lines.append("  price: number;")
    lines.append("  tier: CourseTier;")
    lines.append("  status: CourseStatus;")
    lines.append("  slug: string;")
    lines.append("  modules: ModuleSeed[];")
    lines.append("};")
    lines.append("")
    lines.append("export const COURSES: CourseSeed[] = [")
    for c in courses:
        price_num = re.sub(r"[^0-9.]", "", c["price"]) or "0"
        lines.append("  {")
        lines.append(f"    id: {ts_escape(c['id'])},")
        lines.append(f"    title: {ts_escape(c['title'])},")
        lines.append(f"    promise: {ts_escape(c['promise'])},")
        lines.append(f"    who: {ts_escape(c['who'])},")
        lines.append(f"    price: {price_num},")
        lines.append("    tier: 'single',")
        lines.append(f"    status: {ts_escape(c['status'])},")
        lines.append(f"    slug: {ts_escape(c['slug'])},")
        lines.append("    modules: [")
        for m in c["modules"]:
            lines.append("      {")
            lines.append(f"        num: {m['num']},")
            lines.append(f"        title: {ts_escape(m['title'])},")
            lines.append(f"        framing: {ts_escape(m['framing'])},")
            lines.append("        lessons: [")
            for l in m["lessons"]:
                bullets = ", ".join(ts_escape(b) for b in l["bullets"])
                lines.append("          {")
                lines.append(f"            num: {ts_escape(l['num'])},")
                lines.append(f"            title: {ts_escape(l['title'])},")
                lines.append(f"            durationMin: {l['durationMin']},")
                lines.append(f"            objective: {ts_escape(l['objective'])},")
                lines.append(f"            openingLine: {ts_escape(l['openingLine'])},")
                lines.append(f"            bullets: [{bullets}],")
                lines.append("          },")
            lines.append("        ],")
            wb = ", ".join(ts_escape(w) for w in m["workbookItems"])
            lines.append(f"        workbookItems: [{wb}],")
            lines.append("      },")
        lines.append("    ],")
        lines.append("  },")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    json_dir = sys.argv[1] if len(sys.argv) > 1 else "../output/json"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "../../mobile-app/src/data/seed.ts"

    files = sorted(f for f in os.listdir(json_dir) if f.endswith(".json"))
    if len(files) != len(COURSE_IDS):
        print(f"Warning: found {len(files)} json files, expected {len(COURSE_IDS)}")

    courses = []
    for cid, fname in zip(COURSE_IDS, files):
        data = json.load(open(os.path.join(json_dir, fname), encoding="utf-8"))
        courses.append(build_course(cid, data))

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(emit(courses))

    total_lessons = sum(len(m["lessons"]) for c in courses for m in c["modules"])
    print(f"Wrote {out_path}: {len(courses)} courses, {total_lessons} lessons")
